apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spring-boot-sample-replicaset  # ReplicaSet will be created with this name
  labels:
    replicaset: spring-boot-sample-replicaset
    type: backend-test
spec:
  selector:
    matchLabels:
      type: backend-test
  replicas: 2
  template:
    metadata:
      name: spring-boot-sample-pod
      labels: # custom labels to identify the object (or pod)
        pod: spring-boot-sample-pod
        type: backend-test
        app.kubernetes.io/name: spring-boot-sample-app # to be used as selector by the service
    spec:
      containers:
        - name: spring-boot-sample-k8s-container
          image: rs9893/spring-boot-sample:09282022173059 # image name - to be pulled from Docker Hub
          imagePullPolicy: IfNotPresent # when to pull image - if tag for image is "latest", this will by default be "Always"
          livenessProbe: # to periodically check pod status by doing something (e.g., call one API) and restart the container, on failure
            exec:
              command:
                - '/bin/bash'
                - '-c'
                - >
                  curl --location --request GET 'localhost:5151/sample-app/v1/getAll'
            initialDelaySeconds: 30
            periodSeconds: 30
            terminationGracePeriodSeconds: 5
          readinessProbe: # to periodically pod status by doing something (e.g., call one API) and remove the container, on failure
            httpGet:
              path: /sample-app/v1/getAll
              port: 5151
            initialDelaySeconds: 30
            periodSeconds: 30